services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - dungeongen-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SERVICE_NAME=dungeongen-backend
    env_file:
      - .env
    depends_on:
      - jaeger
    networks:
      - dungeongen-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector
      - "14250:14250"  # gRPC collector
      - "6831:6831/udp"  # UDP agent
      - "6832:6832/udp"  # UDP agent (compact thrift)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_JAEGER_THRIFT_HTTP_PORT=14268
    networks:
      - dungeongen-network

networks:
  dungeongen-network:
    driver: bridge
